// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TCPA.Api.Infrastructure.Data;

namespace TCPA.Api.Infrastructure.Data.Migrations;

[DbContext(typeof(TcpaDbContext))]
partial class TcpaDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TCPA.Api.Domain.ApplicationRegistration", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasColumnName("Id").ValueGeneratedOnAdd();
            b.Property<string>("CoolTextAccountNumber").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("CoolTextAccountNumber");
            b.Property<string>("ApplicationName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("ApplicationName");
            b.Property<string>("CallbackUrl").IsRequired().HasMaxLength(2048).HasColumnType("nvarchar(2048)").HasColumnName("CallbackUrl");
            b.Property<bool>("IsActive").IsRequired().HasDefaultValue(true).HasColumnType("bit").HasColumnName("IsActive");
            b.Property<DateOnly>("OnboardedDate").IsRequired().HasColumnType("date").HasColumnName("OnboardedDate");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("datetime2").HasColumnName("CreatedAt");
            b.Property<DateTime>("UpdatedAt").IsRequired().HasColumnType("datetime2").HasColumnName("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("CoolTextAccountNumber").IsUnique().HasDatabaseName("IX_ApplicationRegistrations_CoolTextAccountNumber");
            b.ToTable("ApplicationRegistrations");
        });

        modelBuilder.Entity("TCPA.Api.Domain.CellNumberOptOutRecord", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasColumnName("Id").ValueGeneratedOnAdd();
            b.Property<string>("CellPhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("CellPhoneNumber");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("Status");
            b.Property<DateTime?>("LastOptOutTimestamp").HasColumnType("datetime2").HasColumnName("LastOptOutTimestamp");
            b.Property<DateTime?>("LastOptInTimestamp").HasColumnType("datetime2").HasColumnName("LastOptInTimestamp");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("datetime2").HasColumnName("CreatedAt");
            b.Property<DateTime>("UpdatedAt").IsRequired().HasColumnType("datetime2").HasColumnName("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("CellPhoneNumber").IsUnique().HasDatabaseName("IX_CellNumberOptOutRecords_CellPhoneNumber");
            b.ToTable("CellNumberOptOutRecords");
        });

        modelBuilder.Entity("TCPA.Api.Domain.AuditLogEntry", b =>
        {
            b.Property<Guid>("RecordId").HasColumnType("uniqueidentifier").HasColumnName("RecordId").ValueGeneratedOnAdd();
            b.Property<string>("EventType").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)").HasColumnName("EventType");
            b.Property<DateTime>("EventTimestamp").IsRequired().HasColumnType("datetime2").HasColumnName("EventTimestamp");
            b.Property<string>("CellPhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("CellPhoneNumber");
            b.Property<string>("OriginatingCoolTextAccountId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("OriginatingCoolTextAccountId");
            b.Property<string>("OriginatingApplicationName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("OriginatingApplicationName");
            b.Property<string?>("OptOutKeywordReceived").HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("OptOutKeywordReceived");
            b.Property<string?>("MessageBody").HasColumnType("nvarchar(max)").HasColumnName("MessageBody");
            b.Property<string>("SystemResponse").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("SystemResponse");
            b.Property<string?>("ConfirmationSmsSentStatus").HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("ConfirmationSmsSentStatus");
            b.Property<DateTime?>("ConfirmationSmsTimestamp").HasColumnType("datetime2").HasColumnName("ConfirmationSmsTimestamp");
            b.Property<string?>("SuppressionReason").HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("SuppressionReason");
            b.Property<string?>("AgentUserId").HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("AgentUserId");
            b.Property<string?>("Reason").HasColumnType("nvarchar(max)").HasColumnName("Reason");
            b.Property<string?>("TicketReference").HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("TicketReference");
            b.Property<string?>("PreviousStatus").HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("PreviousStatus");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("datetime2").HasColumnName("CreatedAt");
            b.HasKey("RecordId");
            b.HasIndex("EventTimestamp").HasDatabaseName("IX_AuditLogEntries_EventTimestamp");
            b.HasIndex("OriginatingApplicationName").HasDatabaseName("IX_AuditLogEntries_ApplicationName");
            b.HasIndex(new[] { "EventType", "EventTimestamp" }).HasDatabaseName("IX_AuditLogEntries_EventType_EventTimestamp");
            b.ToTable("AuditLogEntries");
        });

        modelBuilder.Entity("TCPA.Api.Domain.SmsMessageLog", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasColumnName("Id").ValueGeneratedOnAdd();
            b.Property<string>("CellPhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("CellPhoneNumber");
            b.Property<string>("ApplicationName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("ApplicationName");
            b.Property<string>("Direction").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("Direction");
            b.Property<string?>("MessageContent").HasColumnType("nvarchar(max)").HasColumnName("MessageContent");
            b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)").HasColumnName("Status");
            b.Property<DateTime>("Timestamp").IsRequired().HasColumnType("datetime2").HasColumnName("Timestamp");
            b.HasKey("Id");
            b.HasIndex("Timestamp").HasDatabaseName("IX_SmsMessageLogs_Timestamp");
            b.HasIndex("ApplicationName").HasDatabaseName("IX_SmsMessageLogs_ApplicationName");
            b.ToTable("SmsMessageLogs");
        });
#pragma warning restore 612, 618
    }
}
