using System.ComponentModel.DataAnnotations;

namespace TCPA.Api.Domain;

/// <summary>
/// Represents a registered SCG application in the TCPA compliance system.
/// The Application Registry maps Cool Text account identifiers to the SCG applications
/// that are subject to TCPA enforcement (SPEC-014 / BC-6).
///
/// This entity is the authoritative source for:
/// - Which applications are subject to TCPA opt-out enforcement
/// - The Cool Text account number used by each application
/// - The callback URL for routing inbound non-opt-out SMS replies
/// - Whether the application is currently active (EPIC-006 / STORY-022)
///
/// <para>
/// The Active flag provides a soft-disable mechanism: inactive applications are treated
/// as unregistered by the compliance gate (BR-063), allowing CCB/My Account to be registered
/// at deployment but kept inactive until its TCPA integration is verified (ARCH-RISK-006).
/// </para>
/// </summary>
public sealed class ApplicationRegistration
{
    /// <summary>
    /// Unique system identifier for this application registration record.
    /// Generated by the database on insert.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// The Cool Text account number assigned to this SCG application.
    /// This is the lookup key used on every inbound and outbound message to resolve
    /// which registered application the message belongs to.
    ///
    /// Must be unique across all registrations. Stored encrypted in production
    /// (column-level encryption via Azure SQL Always Encrypted — TASK-061).
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string CoolTextAccountNumber { get; init; } = string.Empty;

    /// <summary>
    /// Human-readable name for this application, used in audit log entries,
    /// compliance reports, and operational logs.
    /// Examples: "GCMA", "KMI Active", "ARM/Construction Portal", "BizTalk", "CCB/My Account".
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string ApplicationName { get; init; } = string.Empty;

    /// <summary>
    /// The HTTPS callback URL to which inbound SMS replies (that are NOT opt-out keywords)
    /// are forwarded for this application. Must use the HTTPS scheme; validated at startup.
    /// </summary>
    [Required]
    [MaxLength(2048)]
    public string CallbackUrl { get; init; } = string.Empty;

    /// <summary>
    /// Controls whether this application participates in TCPA enforcement.
    ///
    /// When true: opt-out status is enforced for all outbound messages sent under this
    /// application's Cool Text account, and inbound replies are routed to <see cref="CallbackUrl"/>.
    ///
    /// When false: the application is treated as unregistered — no enforcement, no inbound
    /// routing. This allows CCB/My Account to be registered at deployment but kept inactive
    /// until its TCPA integration is verified end-to-end (BR-063, ARCH-RISK-006).
    /// </summary>
    public bool IsActive { get; init; }

    /// <summary>
    /// The date on which this application was onboarded into the TCPA compliance system.
    /// Used for audit trail and configuration history.
    /// </summary>
    public DateOnly OnboardedDate { get; init; }

    /// <summary>
    /// UTC timestamp when this registration record was created.
    /// </summary>
    public DateTime CreatedAt { get; init; }

    /// <summary>
    /// UTC timestamp when this registration record was last modified.
    /// Updated on any change to IsActive or other fields.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
