using System.ComponentModel.DataAnnotations;

namespace TCPA.Api.Domain;

/// <summary>
/// Immutable audit log record for a single compliance-relevant event in the TCPA system.
/// This entity captures opt-out events, blocked outbound attempts, and re-opt-in operations
/// with full context to satisfy regulatory and legal audit requirements (SPEC-008, SPEC-009,
/// SPEC-010, BC-4).
///
/// <para>
/// IMMUTABILITY: This entity must never be updated or deleted after creation.
/// Immutability is enforced at two layers:
/// 1. Application layer: <c>IAuditLogRepository</c> exposes only Append methods (no Update/Delete).
/// 2. Database layer: A DDL trigger on the AuditLogEntry table raises an error on any
///    UPDATE or DELETE attempt (TASK-064, ADR-004).
/// </para>
///
/// <para>
/// RETENTION: Records must be retained for a minimum of 5 years from <see cref="EventTimestamp"/>.
/// Records older than 90 days are tiered to Azure Blob Storage WORM containers
/// while remaining queryable for the 5-year window (TASK-066, ADR-004).
/// </para>
///
/// <para>
/// PII: <see cref="CellPhoneNumber"/> is PII and stored encrypted (Always Encrypted,
/// deterministic AES-256). <see cref="MessageBody"/> is PII-adjacent and encrypted at rest
/// via Azure SQL TDE at minimum (ADR-003, NFS-007).
/// </para>
/// </summary>
public sealed class AuditLogEntry
{
    /// <summary>
    /// Unique identifier for this audit record. Generated by the database on insert.
    /// </summary>
    public Guid RecordId { get; init; }

    /// <summary>
    /// The type of compliance event this record documents.
    /// </summary>
    public AuditEventType EventType { get; init; }

    /// <summary>
    /// UTC timestamp of the triggering event.
    /// For opt-out events: the time the inbound opt-out message was received by the webhook.
    /// For blocked outbound events: the time the outbound SMS attempt was made.
    /// For re-opt-in events: the time the Admin API call was processed.
    ///
    /// This is NOT the database write time — it is the business event time.
    /// The 5-year retention window is calculated from this field.
    /// </summary>
    public DateTime EventTimestamp { get; init; }

    /// <summary>
    /// The cell phone number involved in this event, in E.164 format.
    /// PII — stored encrypted with Azure SQL Always Encrypted (deterministic AES-256).
    /// Never log the raw value; always use the masked form (last 4 digits only).
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string CellPhoneNumber { get; init; } = string.Empty;

    /// <summary>
    /// The Cool Text account identifier from the originating message or request.
    /// Used to correlate this audit entry with a specific SCG application.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string OriginatingCoolTextAccountId { get; init; } = string.Empty;

    /// <summary>
    /// The human-readable SCG application name resolved from the Application Registry
    /// at the time of the event (e.g., "GCMA", "KMI Active").
    /// Stored as a snapshot so audit records remain accurate even if the registry is later
    /// reconfigured.
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string OriginatingApplicationName { get; init; } = string.Empty;

    /// <summary>
    /// The opt-out keyword that was detected in the inbound message body.
    /// Populated only for <see cref="AuditEventType.OptOut"/> events.
    /// Null for <see cref="AuditEventType.BlockedOutbound"/> and
    /// <see cref="AuditEventType.ReOptIn"/> events.
    /// </summary>
    [MaxLength(50)]
    public string? OptOutKeywordReceived { get; init; }

    /// <summary>
    /// The SMS message body that triggered this event.
    /// Populated for OptOut and BlockedOutbound events; null for ReOptIn events.
    ///
    /// PII-adjacent — encrypted at rest via Azure SQL TDE (column-level encryption evaluated
    /// per ADR-003). Must not appear in production log output (BR-069).
    /// </summary>
    public string? MessageBody { get; init; }

    /// <summary>
    /// A machine-readable description of the system's response to this event.
    /// Examples:
    /// - "OPT_OUT_STATUS_WRITTEN" — new opt-out recorded
    /// - "ALREADY_OPT_OUT_NO_ACTION" — number was already opted out
    /// - "MESSAGE_SUPPRESSED_OPT_OUT" — outbound blocked due to opt-out status
    /// - "OPT_IN_STATUS_RESTORED" — successful re-opt-in by agent
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string SystemResponse { get; init; } = string.Empty;

    /// <summary>
    /// Indicates whether the opt-out confirmation SMS was sent to the customer.
    /// Populated only for <see cref="AuditEventType.OptOut"/> events; null otherwise.
    /// </summary>
    public ConfirmationSmsStatus? ConfirmationSmsSentStatus { get; init; }

    /// <summary>
    /// UTC timestamp when the confirmation SMS was dispatched (or null if not sent).
    /// Populated only for <see cref="AuditEventType.OptOut"/> events.
    /// </summary>
    public DateTime? ConfirmationSmsTimestamp { get; init; }

    /// <summary>
    /// The reason a message was suppressed, if applicable.
    /// Populated as "OPT_OUT" for <see cref="AuditEventType.BlockedOutbound"/> events.
    /// Null for all other event types.
    /// </summary>
    [MaxLength(100)]
    public string? SuppressionReason { get; init; }

    // --- Re-Opt-In specific fields (populated only for AuditEventType.ReOptIn) ---

    /// <summary>
    /// The identity of the Help Desk agent or Compliance Officer who performed the re-opt-in.
    /// Extracted from the JWT token claim on the Admin API request — never supplied by the caller.
    /// Populated only for <see cref="AuditEventType.ReOptIn"/> events.
    /// </summary>
    [MaxLength(200)]
    public string? AgentUserId { get; init; }

    /// <summary>
    /// The free-text reason provided by the Help Desk agent for this re-opt-in.
    /// Required for re-opt-in events (minimum 20 characters per TASK-029).
    /// Null for all other event types.
    /// </summary>
    public string? Reason { get; init; }

    /// <summary>
    /// An optional ticket or case reference number linked to this re-opt-in action.
    /// Allows correlation with the Help Desk ticketing system.
    /// Null if no ticket reference was provided.
    /// </summary>
    [MaxLength(200)]
    public string? TicketReference { get; init; }

    /// <summary>
    /// The opt-out status the cell number held immediately before this re-opt-in event.
    /// Populated only for <see cref="AuditEventType.ReOptIn"/> events.
    /// </summary>
    public OptOutStatus? PreviousStatus { get; init; }

    /// <summary>
    /// UTC timestamp when this audit record was written to the database.
    /// This is distinct from <see cref="EventTimestamp"/> — it reflects the write time,
    /// not the business event time. Used for operational monitoring.
    /// </summary>
    public DateTime CreatedAt { get; init; }
}
