using System.ComponentModel.DataAnnotations;

namespace TCPA.Api.Domain;

/// <summary>
/// Authoritative record of the current OPT-IN / OPT-OUT status for a single cell phone number.
/// This entity is the primary lookup target for the outbound SMS compliance gate (SPEC-001 / SPEC-006).
///
/// <para>
/// The cell_number field is PII and must be stored with Azure SQL Always Encrypted
/// (deterministic AES-256 encryption) to support indexed equality lookups while keeping
/// the value encrypted at rest (ADR-003, NFS-007, TASK-061).
/// </para>
///
/// <para>
/// Opt-out status is GLOBAL across all applications — a single opt-out from any SCG
/// application suppresses that number across the entire TCPA platform (BR-020 implied by
/// the spec design; no per-application scoping of opt-out status).
/// </para>
///
/// <para>
/// Default behavior: a cell number with no record in this table is treated as OPT_IN (BR-001).
/// This entity is only created when a cell number's status is first explicitly set.
/// </para>
/// </summary>
public sealed class CellNumberOptOutRecord
{
    /// <summary>
    /// Unique system identifier for this opt-out status record.
    /// Generated by the database on insert.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// The cell phone number in E.164 format (e.g., +12025551234).
    /// This field is PII and is stored encrypted (Azure SQL Always Encrypted, deterministic
    /// AES-256). The unique index on this column enables fast equality lookup at the
    /// compliance gate without requiring server-side decryption (ADR-003).
    ///
    /// Never log the raw value of this field. All log output must use the masked form
    /// (last 4 digits only, e.g., "******1234") per BR-068.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string CellPhoneNumber { get; init; } = string.Empty;

    /// <summary>
    /// The current opt-in / opt-out status for this cell number.
    /// This is the value read by the compliance gate on every outbound SMS attempt.
    /// </summary>
    public OptOutStatus Status { get; set; }

    /// <summary>
    /// UTC timestamp of the most recent opt-out event for this cell number.
    /// Null if the number has never opted out (or was only ever directly re-opted-in).
    /// </summary>
    public DateTime? LastOptOutTimestamp { get; set; }

    /// <summary>
    /// UTC timestamp of the most recent re-opt-in event for this cell number.
    /// Null if the number has never been re-opted-in.
    /// </summary>
    public DateTime? LastOptInTimestamp { get; set; }

    /// <summary>
    /// UTC timestamp when this record was first created (i.e., when the cell number
    /// was first seen by the TCPA system — either its first opt-out or first explicit status set).
    /// </summary>
    public DateTime CreatedAt { get; init; }

    /// <summary>
    /// UTC timestamp when the status was most recently changed.
    /// Updated on every OPT_OUT or OPT_IN status transition.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
