using System.ComponentModel.DataAnnotations;

namespace TCPA.Api.Domain;

/// <summary>
/// Represents the direction of an SMS message through the TCPA compliance system.
/// </summary>
public enum SmsDirection
{
    /// <summary>An outbound SMS request received from an SCG application, directed toward a customer.</summary>
    Outbound = 1,

    /// <summary>An inbound SMS reply received from a customer via the Cool Text webhook.</summary>
    Inbound = 2
}

/// <summary>
/// Represents the processing outcome of an SMS message that passed through the TCPA proxy.
/// </summary>
public enum SmsMessageStatus
{
    /// <summary>The outbound message was forwarded to Cool Text for delivery.</summary>
    Forwarded = 1,

    /// <summary>The outbound message was suppressed because the destination number has OPT_OUT status.</summary>
    Suppressed = 2,

    /// <summary>The inbound message was routed to the application callback URL.</summary>
    RoutedToApplication = 3,

    /// <summary>The inbound message triggered opt-out processing (keyword detected).</summary>
    OptOutProcessed = 4,

    /// <summary>The outbound message could not be forwarded due to a Cool Text API error.</summary>
    ForwardFailed = 5,

    /// <summary>The inbound message could not be delivered to the application after retries exhausted.</summary>
    DeliveryFailed = 6
}

/// <summary>
/// Operational log entry for an individual SMS message processed through the TCPA proxy.
/// This table captures message-level telemetry for both inbound and outbound messages,
/// feeding into the compliance reports (SPEC-011, SPEC-012) and the reporting projection
/// database (TASK-040).
///
/// <para>
/// Unlike <see cref="AuditLogEntry"/>, this table is NOT required to be immutable at the
/// database layer — it is operational telemetry. However, records should not be modified
/// after the message processing completes.
/// </para>
///
/// <para>
/// PII: <see cref="CellPhoneNumber"/> is PII and stored encrypted with Azure SQL Always
/// Encrypted (deterministic AES-256). Never log the raw cell number value.
/// </para>
/// </summary>
public sealed class SmsMessageLog
{
    /// <summary>
    /// Unique identifier for this message log entry. Generated by the database on insert.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// The cell phone number involved in this message, in E.164 format.
    /// PII — stored encrypted. Never log the raw value.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string CellPhoneNumber { get; init; } = string.Empty;

    /// <summary>
    /// The human-readable SCG application name associated with this message.
    /// Resolved from the Application Registry at message processing time.
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string ApplicationName { get; init; } = string.Empty;

    /// <summary>
    /// Whether this message was inbound (customer to SCG) or outbound (SCG to customer).
    /// </summary>
    public SmsDirection Direction { get; init; }

    /// <summary>
    /// The SMS message content. Not included in production log output per BR-069.
    /// Available in debug logs only.
    /// </summary>
    public string? MessageContent { get; init; }

    /// <summary>
    /// The outcome of message processing by the TCPA proxy.
    /// </summary>
    public SmsMessageStatus Status { get; init; }

    /// <summary>
    /// UTC timestamp when this message was received and processed by the TCPA system.
    /// For outbound messages, this is when the upstream application submitted the request.
    /// For inbound messages, this is when the Cool Text webhook was received.
    /// </summary>
    public DateTime Timestamp { get; init; }
}
