# Publish-PR.ps1
# Publishes SDLC pipeline output as a GitHub PR.
# Run from the project root after Agent 13 has written outputs/pr-description.md.
#
# Prerequisites:
#   - git remote 'origin' configured
#   - gh CLI installed and authenticated (gh auth login), OR a GITHUB_TOKEN env var
#   - outputs/pr-description.md exists

param(
    [string]$ProductSlug = "",
    [string]$Base = "main"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# --- Resolve project root ---
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

# --- Pre-condition checks ---
$prFile = "outputs\pr-description.md"
if (-not (Test-Path $prFile)) {
    Write-Error "Halted: $prFile not found. Run Agent 13 first."
    exit 1
}

try { git remote get-url origin | Out-Null }
catch {
    Write-Error "Halted: no git remote 'origin' configured. Run: git remote add origin https://github.com/[org]/[repo].git"
    exit 1
}

# --- Derive branch name ---
if (-not $ProductSlug) {
    # Try to extract product name from PR description heading
    $heading = Select-String -Path $prFile -Pattern "^# PR: (.+)" | Select-Object -First 1
    if ($heading) {
        $ProductSlug = $heading.Matches[0].Groups[1].Value `
            -replace '[^a-zA-Z0-9\s]', '' `
            -replace '\s+', '-' `
            -replace '-+', '-' `
            -replace '^-|-$', '' `
            | ForEach-Object { $_.ToLower() }
        # Truncate to 40 chars
        if ($ProductSlug.Length -gt 40) { $ProductSlug = $ProductSlug.Substring(0, 40).TrimEnd('-') }
    } else {
        $ProductSlug = "pipeline-delivery"
    }
}

$date      = Get-Date -Format "yyyyMMdd"
$branch    = "pipeline/$ProductSlug-$date"
$prTitle   = (Select-String -Path $prFile -Pattern "^# PR: (.+)" | Select-Object -First 1).Matches[0].Groups[1].Value

Write-Host "Branch : $branch"
Write-Host "Title  : $prTitle"
Write-Host "Base   : $base"
Write-Host ""

# --- Check there is actually new output to push ---
$newOutput = @(git status --porcelain -- src/ tests/ 2>$null)
if ($newOutput.Count -eq 0) {
    Write-Host "Nothing new in src/ or tests/ — no untracked or modified files."
    Write-Host "This happens when generated code was already committed directly to $Base."
    Write-Host "Skipping publish — code is already delivered. Run again after the next pipeline produces new output."
    exit 0
}

# --- Git operations ---
Write-Host ">> Checking out $Base and pulling..."
git checkout $Base
git pull origin $Base

Write-Host ">> Creating branch $branch..."
git checkout -b $branch

Write-Host ">> Staging pipeline outputs..."
$toStage = @("src", "tests", "outputs/docs", "outputs/pr-description.md", "outputs/task-log.md")
foreach ($path in $toStage) {
    if (Test-Path $path) { git add $path }
}

# Extract one-line summary from PR description (first non-empty line after Summary heading)
$summary = ""
$inSummary = $false
foreach ($line in Get-Content $prFile) {
    if ($line -match "^## Summary") { $inSummary = $true; continue }
    if ($inSummary -and $line.Trim() -ne "" -and $line -notmatch "^##") {
        $summary = $line.Trim()
        break
    }
}
if (-not $summary) { $summary = $prTitle }

$commitMsg = @"
feat($ProductSlug): pipeline delivery -- $prTitle

Generated by SDLC pipeline Agent 13.
Source PRD: inputs/prd.md
$summary
"@

Write-Host ">> Committing..."
git commit -m $commitMsg

Write-Host ">> Pushing branch..."
git push -u origin $branch

# --- Create PR ---
Write-Host ">> Creating GitHub PR..."

# Strip the HTML comment header from pr-description for the PR body
$prBody = (Get-Content $prFile -Raw) -replace '(?s)<!--.*?-->\s*', ''

# Try gh CLI first
$ghAvailable = $null -ne (Get-Command gh -ErrorAction SilentlyContinue)

if ($ghAvailable) {
    $tempBody = [System.IO.Path]::GetTempFileName()
    Set-Content -Path $tempBody -Value $prBody -Encoding utf8
    gh pr create --title $prTitle --body-file $tempBody --head $branch --base $Base
    Remove-Item $tempBody
} elseif ($env:GITHUB_TOKEN) {
    # GitHub REST API fallback
    $remote  = git remote get-url origin
    if ($remote -match "github\.com[:/](.+?)(?:\.git)?$") {
        $repoPath = $Matches[1]
    } else {
        Write-Error "Could not parse repo path from remote: $remote"
        exit 1
    }

    $payload = @{
        title = $prTitle
        body  = $prBody
        head  = $branch
        base  = $Base
        draft = $false
    } | ConvertTo-Json -Depth 5

    $response = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$repoPath/pulls" `
        -Method Post `
        -Headers @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            Accept        = "application/vnd.github+json"
            "X-GitHub-Api-Version" = "2022-11-28"
        } `
        -Body $payload `
        -ContentType "application/json"

    Write-Host ""
    Write-Host "PR published: $($response.html_url)"
} else {
    Write-Host ""
    Write-Host "Neither gh CLI nor GITHUB_TOKEN found. Run manually:"
    Write-Host "  gh pr create --title '$prTitle' --body-file outputs/pr-description.md --head $branch --base $Base"
    exit 0
}

Write-Host ""
Write-Host "Done. Branch: $branch"
Write-Host "Ready for human review and approval. Do not merge without explicit approval."
